language: csharp
dist: xenial
sudo: required
mono: none
dotnet: 2.2.105

script:
 - dotnet --info
 - dotnet restore
 - dotnet test -v n AaronLuna.AsyncSocketServerTest/AaronLuna.AsyncSocketServerTest.csproj