language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.1.302

script:
 - dotnet --info
 - dotnet restore
 - dotnet test -v n AaronLuna.AsyncFileServerTest/AaronLuna.AsyncFileServerTest.csproj