os: Visual Studio 2017
build: off

environment:
  COVERALLS_REPO_TOKEN:
    secure: /u9GxWoJiR6ovfJc0RVLiV7YxRgOu1Hp6SJtethG2+K8GfOeC2+LxwIR9QcP/ujt

before_build:
  - git submodule update --init --recursive
  - dotnet --info
  - dotnet restore

build_script:
  - dotnet build

test_script:
  - ps: iex ((Get-ChildItem ($env:USERPROFILE + '\.nuget\packages\opencover'))[0].FullName + '\tools\OpenCover.Console.exe' + ' -register:user -target:"dotnet.exe" -targetargs:" test --no-build -v n .\AaronLuna.AsyncFileServerTest\AaronLuna.AsyncFileServerTest.csproj" -filter:"+[AaronLuna.AsyncFileServer.*]* -[AaronLuna.AsyncFileServerTest]*" -output:".\GeneratedReports\CodeCoverageReport.xml" -mergebyhash -skipautoprops -oldstyle')
  - ps: iex ((Get-ChildItem ($env:USERPROFILE + '\.nuget\packages\coveralls.io'))[0].FullName + '\tools\coveralls.net.exe' + ' --opencover .\GeneratedReports\CodeCoverageReport.xml')